[project]
name = "invenio-ae-cli"
version = "0.1"

dependencies = [
	     "invenio-cli"
	     ]

[project.scripts]
invenio-ae-cli = "invenio_ae_cli:cli"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
